name: hello-world-cf
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
            
      - name: Secret Scanning
        uses: gitleaks/gitleaks-action@v2
        
      - name: SAST
        run: echo "SAST"
        
      - name: Docker Image
        run: docker build -t varshaatdockerhub/branch-cf-devsecops-demo .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'docker.io/varshaatdockerhub/branch-cf-devsecops-demo:latest'
          format: 'table'
      
      - name: DockerHub
        run: echo "DockerHub"
        
      - name: DAST - ZAP
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'https://ginandjuice.shop/'

     
     
