name: hello-world-cf
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Secret Scanning
        uses: gitleaks/gitleaks-action@v2
        
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v3.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=santhosh-devops-demo
            -Dsonar.projectKey=santhosh-devops-demo_sysfoo
            -Dsonar.sources=.
            -Dsonar.verbose=true
            -Dsonar.language=java
            -Dsonar.java.binaries=./target/classes
        
      - name: Docker Image
        run: docker build -t varshaatdockerhub/cf-sysfoo .
